# Generated by Django 5.0 on 2023-12-17 15:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_alter_contact_options_productimage'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productimage',
            old_name='image2',
            new_name='image',
        ),
        migrations.RemoveField(
            model_name='productimage',
            name='image1',
        ),
        migrations.RemoveField(
            model_name='productimage',
            name='image3',
        ),
        migrations.RemoveField(
            model_name='productimage',
            name='image4',
        ),
    ]
